lib/db_project_web/router.ex
defmodule DbProjectWeb.Router do
  use DbProjectWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DbProjectWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DbProjectWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/user", DbProjectWeb do
    pipe_through :browser
    get "/show", UserController, :show
    get "/edit", UserController, :edit
    patch "/update", UserController, :update
    put "/update", UserController, :update
    delete "/delete", UserController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api", DbProjectWeb do
    pipe_through :api

    resources "/events", EventController, only: [:index, :show]
    resources "/former_members", FormerMemberController, only: [:index, :show]
    resources "/members", MemberController, only: [:index, :show]
  end

  scope "/auth", DbProjectWeb do
    pipe_through :browser

    post "/", AuthController, :login
    delete "/logout", AuthController, :logout

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  scope "/admin", DbProjectWeb, as: :admin do
    pipe_through :browser

    resources "/events", Admin.EventController
    resources "/roles", Admin.RoleController, only: [:index, :create, :new, :delete]
    resources "/user", Admin.UserController, only: [:index, :edit, :update]
    resources "/former_member", Admin.FormerMemberController, only: [:index, :create, :new, :edit, :update, :delete]
    resources "/member", Admin.MemberController, only: [:index, :delete]
  end

end

lib/db_project_web/views/layout_view.ex
defmodule DbProjectWeb.LayoutView do
  use DbProjectWeb, :view
end

lib/db_project_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello DbProject!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if has_role?(@conn, :user_admin) do %>
              <li>
                <%= link("Users", to: admin_user_path(@conn, :index), class: "btn btn-primary") %>
              </li>
              <li>
                <%= link("Roles", to: admin_role_path(@conn, :index), class: "btn btn-primary") %>
              </li>
            <%= end %>
            <%= if has_role?(@conn, :event_admin) do %>
              <li>
                <%= link("Events", to: admin_event_path(@conn, :index), class: "btn btn-primary") %>
              </li>
            <%= end %>
            <%= if has_role?(@conn, :former_member_admin) do %>
              <li>
                <%= link("Former Members", to: admin_former_member_path(@conn, :index), class: "btn btn-primary") %>
              </li>
            <%= end %>
            <li>
              <%= if is_logged?(@conn) do
                link("Profile", to: user_path(@conn, :show), class: "btn btn-primary")
              end%>
          </li>
            <li>
              <%= if is_logged?(@conn) do
                link("Logout", to: auth_path(@conn, :logout), method: :delete, class: "btn btn-danger")
              else
                link("Login", to: auth_path(@conn, :login), method: :post, class: "btn btn-primary")
              end %>
            </li>
          </ul>
        </nav>
        <span class="logo"></span>
        <span>DB Project</span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/phoenix_html.js") %>"></script>
  </body>
</html>